In [19]:
import pandas  as pd
import numpy  as np

In [20]:
#垃圾分类
#读取文件：
sms_raw  = pd. read_csv("sms_spam.csv",encoding="gbk")
sms_raw


type                                               text
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5562  spam  This is the 2nd time we have tried 2 contact u...
5563   ham               Will ü b going to esplanade fr home?
5564   ham  Pity, * was in mood for that. So...any other s...
5565   ham  The guy did some bitching but I acted like i'd...
5566   ham                         Rofl. Its true to its name

[5567 rows x 2 columns]

In [21]:

#进行数据预处理:
#将特殊字符去掉，并且全部转成小写：
import string
normal_char = string.punctuation+"0987654321"
label = str.maketrans('','',normal_char)
def process(x):
    #（被替换的单词，替换的单词，删掉的单词）
    text1 = x.translate(label)
    text1 = text1.lower()
    return text1
sms_raw['text']  = sms_raw['text'].apply(process)
sms_raw['text']


0       go until jurong point crazy available only in ...
1                                 ok lar joking wif u oni
2       free entry in  a wkly comp to win fa cup final...
3             u dun say so early hor u c already then say
4       nah i dont think he goes to usf he lives aroun...
                              ...                        
5562    this is the nd time we have tried  contact u u...
5563                  will ü b going to esplanade fr home
5564    pity  was in mood for that soany other suggest...
5565    the guy did some bitching but i acted like id ...
5566                            rofl its true to its name
Name: text, Length: 5567, dtype: object

In [22]:
#进行数据预处理:
sms_raw['type'].factorize()
#(array([0, 0, 1, ..., 0, 0, 0]), Index(['ham', 'spam'], dtype='object'))

(array([0, 0, 1, ..., 0, 0, 0]), Index(['ham', 'spam'], dtype='object'))

In [23]:

#统计单词的词频率：
#对于每一个训练文本，它只考虑每种词汇在该训练文本中出现的频率。
from sklearn.feature_extraction.text import  CountVectorizer
cv = CountVectorizer(decode_error='ignore',min_df=100,stop_words='english')
#min_df 是出现最少的次数
cv_fit = cv.fit_transform(sms_raw['text'])
array = cv_fit.toarray()




In [24]:
#这个是取出单词并且进行处理
labels = cv.get_feature_names()


/Users/zhuhe/miniforge3/envs/python_spring02/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [25]:
sms_count_df = pd.DataFrame(data =array,columns=labels)



In [26]:
sms_count_df


claim  come  da  day  dear  did  dont  free  going  good  ...  stop  \
0         0     0   0    0     0    0     0     0      0     0  ...     0   
1         0     0   0    0     0    0     0     0      0     0  ...     0   
2         0     0   0    0     0    0     0     1      0     0  ...     0   
3         0     0   0    0     0    0     0     0      0     0  ...     0   
4         0     0   0    0     0    0     1     0      0     0  ...     0   
...     ...   ...  ..  ...   ...  ...   ...   ...    ...   ...  ...   ...   
5562      1     0   0    0     0    0     0     0      0     0  ...     0   
5563      0     0   0    0     0    0     0     0      1     0  ...     0   
5564      0     0   0    0     0    0     0     0      0     0  ...     0   
5565      0     0   0    0     0    1     0     1      0     0  ...     0   
5566      0     0   0    0     0    0     0     0      0     0  ...     0   

      tell  text  think  time  today  txt  ur  want  week  
0        0     0      0     0      0    0   0     0     0  
1        0     0      0     0      0    0   0     0     0  
2        0     1      0     0      0    1   0     0     0  
3        0     0      0     0      0    0   0     0     0  
4        0     0      1     0      0    0   0     0     0  
...    ...   ...    ...   ...    ...  ...  ..   ...   ...  
5562     0     0      0     1      0    0   0     0     0  
5563     0     0      0     0      0    0   0     0     0  
5564     0     0      0     0      0    0   0     0     0  
5565     0     0      0     0      0    0   0     0     1  
5566     0     0      0     0      0    0   0     0     0  

[5567 rows x 45 columns]

In [27]:
#以上是预处理的过程，结束



In [31]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(sms_count_df,sms_raw['type'],test_size=0.3)

In [33]:
from sklearn.naive_bayes import MultinomialNB
sms_classifier = MultinomialNB().fit(x_train,y_train)
sms_classifier.score(x_test,y_test)

0.9371633752244165

In [35]:
pridect =sms_classifier.predict(x_test)
from  sklearn import metrics
metrics.confusion_matrix(y_test,pridect)


array([[1421,   24],
       [  81,  145]])

In [36]:
print(metrics.classification_report(y_test,pridect))


              precision    recall  f1-score   support

         ham       0.95      0.98      0.96      1445
        spam       0.86      0.64      0.73       226

    accuracy                           0.94      1671
   macro avg       0.90      0.81      0.85      1671
weighted avg       0.93      0.94      0.93      1671



In [ ]:

#完成了

